---

- name: Homebrew tap
  community.general.homebrew_tap:
    name: "{{ item }}"
    state: "present"
  with_items: "{{ brew_taps }}"

- name: Install Homebrew Cask Packages
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: "present"
    install_options: "appdir=/Applications"
    accept_external_apps: true
  with_items: "{{ brew_casks }}"

- name: Install Homebrew Packages
  community.general.homebrew:
    name: "{{ item }}"
    state: "present"
  with_items: "{{ brew_packages }}"
