---

- name: Get stat of Prezto
  ansible.builtin.stat:
    path: ~/.zprezto
  register: zprezto_files
- name: Clone Prezto
  ansible.builtin.git:
    repo: https://github.com/sorin-ionescu/prezto.git
    dest: ~/.zprezto
    recursive: true
  when: zprezto_files.stat.isdir is not defined
# - name: Init Prezto
#   command: setopt EXTENDED_GLOB; for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N)\do; ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"\done

- name: Copy zshrc
  ansible.builtin.copy:
    src: roles/dotfiles/files/.zshrc
    dest: ~/
    mode: u+rwx

- name: Copy an entrypoint for Fork
  ansible.builtin.copy:
    src: roles/dotfiles/files/.fork-entrypoint.sh
    dest: ~/
    mode: u+rwx
