---

- name: Setup python
  shell: LDFLAGS="-L$(xcrun --show-sdk-path)/usr/lib" pyenv install -f 3.8.6 && pyenv global 3.8.6

- name: Upgrade pip
  command: pip install pip --upgrade

- name: Install fundamental packages
  pip:
    name:
      - ansible-lint
      - setuptools
      - wheel
