---
- hosts: default
  connection: local
  roles:
    - brew
    - appstore
    - dotfiles
    - nodejs
    - python
    - go

- hosts: for-jobs
  connection: local
  roles:
    - brew
    - appstore
    - dotfiles
    - nodejs
    - python
    - go
