---

- name: Register installed apps list
  command: mas list
  register: installed_list
  check_mode: false
  changed_when: false

- name: Install App Store applications
  command: mas install "{{ item }}"
  when: "installed_list.stdout_lines | select('search', item) | list | length == 0 and not installed_list is skipped"
  with_items: "{{ apps_list }}"
