---

- name: Register installed apps list
  command: mas list
  register: installed_list
  changed_when: false

# - debug:
#     msg: "{{ installed_list.stdout_lines | select('search', 497799835) }}"

- name: Install App Store applications
  command: mas install "{{ item }}"
  with_items: "{{ apps_list }}"
